// Generated by https://quicktype.io

export interface Car {
  car_id:             number;
  server_value:       number;
  car_name:           string;
  year:               number;
  class:              string;
  server_value_2:     string;
  sim_id:             number;
  non_base_content:   number;
  content_link:       null | string;
  content_link_name:  null | string;
  additional_content: unknown[];
}
