// Generated by https://quicktype.io

export interface Track {
  track_id: number;
  track_name: string;
  track_year: number;
  acc_track_name: string;
  thumbnail: string;
  trackmap: string;
  country: string;
  turns: number;
  km: number;
  track_guide_video: string;
  turn_factor: string;
  city: string;
  openweather_city_id: number | null;
  sim_id: number;
  non_base_content: number;
  content_link: null | string;
  content_link_name: null | string;
  sim_settings: string;
}
