import { Track } from './track';

// Generated by https://quicktype.io

export interface UpcomingSession {
  data: Datum[];
}

export interface Datum {
  race_id: number;
  server_region: ServerRegion;
  race_date: string;
  season_week: number;
  real_weather: boolean;
  server_name: string;
  server_password: ServerPassword;
  weather_settings: WeatherSettings;
  start_times: SessionsLength;
  sessions_length: SessionsLength;
  pitstop_settings: PitstopSettings;
  track: Track;
  slots: number;
  registered: number;
  signupCloses: string;
  signOutCloses: string;
  signupStart: string;
  signedUp: boolean;
  session_broadcaster: any[];
  isLive: number;
  serverLive: number;
}

export interface PitstopSettings {
  pitstop_required: boolean;
  driver_stint_time: number;
  fixed_refueling_time: boolean;
  refueling_required: boolean;
  driver_swap_required: boolean;
  tyre_change_required: boolean;
  pitwindow: number;
}

export enum ServerPassword {
  Lfm = 'lfm',
}

export enum ServerRegion {
  Eu = 'EU',
}

export interface SessionsLength {
  p: number;
  q: number;
  r: number;
}

export interface WeatherSettings {
  ambientTemp: number;
  cloudLevel: number;
  rain: number;
  weatherRandomness: number;
}
